use_frameworks!

platform :ios, '10.0'

target 'ConstructorDI_Example' do
  pod 'DIContainer', :path => '../../DIContainer'

  target 'ConstructorDI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
