use_frameworks!

platform :ios, '10.0'

target 'MethodDI_Example' do
  pod 'MethodDI', :path => '../'

  pod 'DIContainer', :path => '../../DIContainer'

  target 'MethodDI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
